### ISSUE TITLE
How to bind a crystal closure to c library

### ISSUE THREAD

**Issue by raydf** [manastech/crystal#2029]
Hello:

Using DukTape (Javascript embedded engine):

```
dependencies:
  duktape:
    github: jessedoyle/duktape.cr
    version: ~> 0.7.0
```
I tested this code:

```crystal
  sbx = Duktape::Sandbox.new

  sbx.push_global_object

  test = 10
  sbx.push_proc(2) do |ptr| # 2 stack arguments
    env = Duktape::Sandbox.new ptr
    a = env.get_number 0
    test = env.get_number 1
    env.push_number a + test
    env.return 1 # return success
  end

  sbx.put_prop_string -2, "adder"
  sbx.eval! "print(adder(2, 3));" # => 5
```

this returns

```
passing a closure to C is not allowed
```

Any help on how can i achieve the closures usage i a c binding?
